name: Main

on:
  workflow_dispatch:
    inputs:
      name:
        required: true
        description: The name of the group to create

permissions:
  id-token: write

jobs:
  poc:
    name: PoC
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '17'

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: node index.js $NAME
        env:
          NAME: ${{ github.event.inputs.name }}
          TENANT_ID: ${{ fromJSON(secrets.AZURE_CREDENTIALS).tenantId }}
          CLIENT_ID: ${{ fromJSON(secrets.AZURE_CREDENTIALS).clientId }}
          CLIENT_SECRET: ${{ fromJSON(secrets.AZURE_CREDENTIALS).clientSecret }}